on:
    push:
      branches:
        - main

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        - 
            name: Build Docker Image
            run: |
                docker build -t ${{ vars.DOCKERHUB_USERNAME }}/lanchain:latest .
        - 
            name: Tag Docker Image
            run: |
                docker tag ${{ vars.DOCKERHUB_USERNAME }}/lanchain:latest ${{ vars.DOCKERHUB_USERNAME }}/lanchain:${{ github.sha }}
        - 
            name: Push Docker Image (latest)
            run: |
                docker push ${{ vars.DOCKERHUB_USERNAME }}/lanchain:latest
        - 
            name: Push Docker Image (commit SHA)
            run: |
                docker push ${{ vars.DOCKERHUB_USERNAME }}/lanchain:${{ github.sha }}        